In [2]:
import torch
import numpy as np

In [9]:
x = torch.tensor([[2,3], [4,5]])
y = torch.tensor([[4,12], [3,67]])
x.add_(3)
print("zero tensor:", torch.zeros(2,3))
print("random tensor:", torch.rand(2,3))
print(x)
print(x+y)
print(torch.matmul(x,y))
print(x.dtype)
print(y.shape)
print(x.device)


zero tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])
random tensor: tensor([[0.7256, 0.6344, 0.6304],
        [0.7947, 0.3214, 0.6200]])
tensor([[5, 6],
        [7, 8]])
tensor([[ 9, 18],
        [10, 75]])
tensor([[ 38, 462],
        [ 52, 620]])
torch.int64
torch.Size([2, 2])
cpu
